version: '3.1'
services:

  jenkinmaster:
    image: jenkin-master
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8484:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home: