version: '3.1'
services:

  jenkinmaster:
    image: jenkin-master
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8484:8080
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://dind:2375
    depends_on:
      - dind

  dind:
    image: docker:dind
    restart: always
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command:
      - --storage-driver=overlay2

volumes:
  jenkins_home: